// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7XG_EP8jfGe-inBEzRcImEPB9OUJGNE',
    appId: '1:497575487762:web:08649d786c64b24f062bcb',
    messagingSenderId: '497575487762',
    projectId: 'fooddeliveryapp-c9e8f',
    authDomain: 'fooddeliveryapp-c9e8f.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c9e8f.appspot.com',
    measurementId: 'G-RJDQ11NEVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQshXS2jYDzhW70MjLjdcLQsvD6lqg98',
    appId: '1:497575487762:android:b7fc8ad906a8bd6a062bcb',
    messagingSenderId: '497575487762',
    projectId: 'fooddeliveryapp-c9e8f',
    storageBucket: 'fooddeliveryapp-c9e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5xjbrL7F-qtdA0V67nuPNyUcMLCiILJg',
    appId: '1:497575487762:ios:40c72370185e488c062bcb',
    messagingSenderId: '497575487762',
    projectId: 'fooddeliveryapp-c9e8f',
    storageBucket: 'fooddeliveryapp-c9e8f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5xjbrL7F-qtdA0V67nuPNyUcMLCiILJg',
    appId: '1:497575487762:ios:40c72370185e488c062bcb',
    messagingSenderId: '497575487762',
    projectId: 'fooddeliveryapp-c9e8f',
    storageBucket: 'fooddeliveryapp-c9e8f.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS7XG_EP8jfGe-inBEzRcImEPB9OUJGNE',
    appId: '1:497575487762:web:b31b1fed2b6b8043062bcb',
    messagingSenderId: '497575487762',
    projectId: 'fooddeliveryapp-c9e8f',
    authDomain: 'fooddeliveryapp-c9e8f.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c9e8f.appspot.com',
    measurementId: 'G-02QJ6HQM07',
  );
}
